### ISSUE TITLE
Statistic Class To High

### ISSUE THREAD

**Issue by JTnadrooi** [JTnadrooi/Amphibole#2]
The stat class is way higher than the pixel art example. Changing the ``height`` causes a visual error.

**Comment by JTnadrooi** [comment]
Fixed with changing the ``line-height`` property.

**Comment by userdaniel083** [comment]
Als het karakter tegen de canvas aan de boven- en linkerzijde gaat. Kan je de border niet verlaten.

**Comment by userdaniel083** [comment]
Gaat door collision heen.

**Comment by userdaniel083** [comment]
Stat class is veel te hoog. (Gefixt door lineheight aan te passen.)
